package com.wemakestuff.podstuff.ui;

import android.os.Bundle;

import com.wemakestuff.podstuff.R;
import com.wemakestuff.podstuff.model.api.Episode;
import com.wemakestuff.podstuff.model.api.EpisodeCategory;
import com.wemakestuff.podstuff.model.api.Podcast;
import com.wemakestuff.podstuff.model.navigation.EpisodeCategoryItem;
import com.wemakestuff.podstuff.model.navigation.EpisodeItem;
import com.wemakestuff.podstuff.model.navigation.Item;
import com.wemakestuff.podstuff.model.navigation.PodcastItem;
import com.wemakestuff.podstuff.model.navigation.listener.OnEpisodeClickListener;
import com.wemakestuff.podstuff.model.navigation.listener.OnPodcastClickListener;
import com.wemakestuff.podstuff.ui.base.BaseListActivity;
import com.wemakestuff.podstuff.ui.widget.adapter.ItemAdapter;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PodcastListActivity extends BaseListActivity implements OnPodcastClickListener {
    ItemAdapter mAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.item_list);

        List<Item> itemList = new ArrayList<Item>();
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), this));

        mAdapter = new ItemAdapter(this, itemList);
        setListAdapter(mAdapter);
    }

    @Override
    public void onPodcastClick(Podcast podcast, Action action) {

    }
}
