package com.wemakestuff.teracast.ui.widget.adapter;

import android.content.Context;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;

import com.wemakestuff.teracast.model.api.Episode;
import com.wemakestuff.teracast.model.api.Network;
import com.wemakestuff.teracast.model.api.Podcast;
import com.wemakestuff.teracast.model.navigation.Item;
import com.wemakestuff.teracast.model.navigation.PodcastItem;
import com.wemakestuff.teracast.model.navigation.listener.OnPodcastClickListener;
import com.wemakestuff.teracast.ui.podcasts.PodcastListFragment;
import com.wemakestuff.teracast.util.Ln;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Random;

public class PodcastListPagerAdapter extends FragmentPagerAdapter {
    static List<Episode> episodeList;
    static List<Item> itemList;
    Context mContext;

    public PodcastListPagerAdapter(Context mContext, FragmentManager fragmentManager) {
        super(fragmentManager);
        this.mContext = mContext;
    }

    public static List<Episode> getEpisodes() {
        if (episodeList == null) {
            episodeList = new ArrayList<Episode>();
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
            episodeList.add(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L));
        }
        return episodeList;
    }

    public static List<Item> getPodcastItems(OnPodcastClickListener mListener) {
        if (itemList == null) {
            itemList = new ArrayList<Item>();
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
            itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", new Network("Startups For the Rest of Us", "Mike Taber and Rob Walling")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg", new Network("This Week in Tech", "Leo Laporte and guests talk about coffee, books, and oh yeah Tech!")), mListener));
            itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg", new Network("This Week In", "Jason talks about things...and stuff")), mListener));
            itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", new Network("Answer Me This", "Helen and Ollie answer listener questions, with occasional help from Martin the sound man!")), mListener));
        }

        long seed = System.nanoTime();
        Collections.shuffle(itemList, new Random(seed));
        return itemList;
    }

    @Override
    public Fragment getItem(int position) {
        switch (position) {
            case 0:
                PodcastListFragment podcastListFragment = new PodcastListFragment();
                podcastListFragment.setItems(getPodcastItems(podcastListFragment));
                return podcastListFragment;
            case 1:
                PodcastListFragment podcastListFragment2 = new PodcastListFragment();
                podcastListFragment2.setItems(getPodcastItems(podcastListFragment2));
                return podcastListFragment2;
            case 2:
                PodcastListFragment podcastListFragment3 = new PodcastListFragment();
                podcastListFragment3.setItems(getPodcastItems(podcastListFragment3));
                return podcastListFragment3;
        }
        Ln.d("Returning Null");
        return null;
    }

    @Override
    public int getCount() {
        return 3;
    }

    @Override
    public CharSequence getPageTitle(int position) {
        switch (position) {
            case 0:
                return "All";
            case 1:
                return "Some";
            case 2:
                return "More";
            default:
                return null;
        }
    }
}
