package com.wemakestuff.podstuff.ui.widget.adapter;

import android.content.Context;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;

import com.wemakestuff.podstuff.model.api.Episode;
import com.wemakestuff.podstuff.model.api.EpisodeCategory;
import com.wemakestuff.podstuff.model.api.Podcast;
import com.wemakestuff.podstuff.model.navigation.EpisodeCategoryItem;
import com.wemakestuff.podstuff.model.navigation.EpisodeItem;
import com.wemakestuff.podstuff.model.navigation.Item;
import com.wemakestuff.podstuff.model.navigation.PodcastItem;
import com.wemakestuff.podstuff.model.navigation.listener.OnEpisodeClickListener;
import com.wemakestuff.podstuff.model.navigation.listener.OnPodcastClickListener;
import com.wemakestuff.podstuff.ui.podcasts.PodcastDetailEpisodeListFragment;
import com.wemakestuff.podstuff.ui.podcasts.PodcastDetailFragment;
import com.wemakestuff.podstuff.ui.podcasts.PodcastListFragment;
import com.wemakestuff.podstuff.util.Ln;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Random;

public class PodcastDetailPagerAdapter extends FragmentPagerAdapter {
    Context mContext;

    public PodcastDetailPagerAdapter(Context mContext, FragmentManager fragmentManager) {
        super(fragmentManager);
        this.mContext = mContext;
    }

    @Override
    public Fragment getItem(int position) {
        switch (position) {
            case 0:
                PodcastDetailEpisodeListFragment episodeListFragment = new PodcastDetailEpisodeListFragment();
                episodeListFragment.setItems(getEpisodeItems(episodeListFragment));
                episodeListFragment.setPodcast(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"));
                return episodeListFragment;
            case 1:
                PodcastDetailFragment podcastDetailFragment = new PodcastDetailFragment();
                podcastDetailFragment.setPodcast(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"));
                return podcastDetailFragment;
            case 2:
                PodcastListFragment podcastListFragment = new PodcastListFragment();
                podcastListFragment.setItems(getPodcastItems(podcastListFragment));
                return podcastListFragment;
        }
        Ln.d("Returning Null");
        return null;
    }

    @Override
    public int getCount() {
        return 3;
    }

    @Override
    public CharSequence getPageTitle(int position) {
        switch (position) {
            case 0:
                return "Episodes";
            case 1:
                return "Deets";
            case 2:
                return "Related Podcasts";
            default:
                return null;
        }
    }

    protected List<Item> getEpisodeItems(OnEpisodeClickListener mListener) {
        List<Item> itemList = new ArrayList<Item>();
        itemList.add(new EpisodeCategoryItem(new EpisodeCategory("TOP EPISODES")));
        itemList.add(new EpisodeItem(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 151 | Getting Paid Before You Build, Dealing with Entrpreneurial Angst, Figuring Out How Much to Charge and More Listener Questions", "Mike and Rob answer listener questions on getting paid before you build, dealing with entrpreneurial angst, figuring out how much to charge and more. They also give updates on AuditShark and Drip.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/ItC9pm9Hx0s\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://media.blubrry.com/startupsrestofus/www.project98.com/podcast/startups-for-the-rest-of-us-151.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 151 | Getting Paid Before You Build, Dealing with Entrpreneurial Angst, Figuring Out How Much to Charge and More Listener Questions", "Mike and Rob answer listener questions on getting paid before you build, dealing with entrpreneurial angst, figuring out how much to charge and more. They also give updates on AuditShark and Drip.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/ItC9pm9Hx0s\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://media.blubrry.com/startupsrestofus/www.project98.com/podcast/startups-for-the-rest-of-us-151.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeCategoryItem(new EpisodeCategory("ALL EPISODES")));
        itemList.add(new EpisodeItem(new Episode("Episode 151 | Getting Paid Before You Build, Dealing with Entrpreneurial Angst, Figuring Out How Much to Charge and More Listener Questions", "Mike and Rob answer listener questions on getting paid before you build, dealing with entrpreneurial angst, figuring out how much to charge and more. They also give updates on AuditShark and Drip.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/ItC9pm9Hx0s\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://media.blubrry.com/startupsrestofus/www.project98.com/podcast/startups-for-the-rest-of-us-151.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 151 | Getting Paid Before You Build, Dealing with Entrpreneurial Angst, Figuring Out How Much to Charge and More Listener Questions", "Mike and Rob answer listener questions on getting paid before you build, dealing with entrpreneurial angst, figuring out how much to charge and more. They also give updates on AuditShark and Drip.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/ItC9pm9Hx0s\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://media.blubrry.com/startupsrestofus/www.project98.com/podcast/startups-for-the-rest-of-us-151.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 151 | Getting Paid Before You Build, Dealing with Entrpreneurial Angst, Figuring Out How Much to Charge and More Listener Questions", "Mike and Rob answer listener questions on getting paid before you build, dealing with entrpreneurial angst, figuring out how much to charge and more. They also give updates on AuditShark and Drip.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/ItC9pm9Hx0s\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://media.blubrry.com/startupsrestofus/www.project98.com/podcast/startups-for-the-rest-of-us-151.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 151 | Getting Paid Before You Build, Dealing with Entrpreneurial Angst, Figuring Out How Much to Charge and More Listener Questions", "Mike and Rob answer listener questions on getting paid before you build, dealing with entrpreneurial angst, figuring out how much to charge and more. They also give updates on AuditShark and Drip.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/ItC9pm9Hx0s\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://media.blubrry.com/startupsrestofus/www.project98.com/podcast/startups-for-the-rest-of-us-151.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 151 | Getting Paid Before You Build, Dealing with Entrpreneurial Angst, Figuring Out How Much to Charge and More Listener Questions", "Mike and Rob answer listener questions on getting paid before you build, dealing with entrpreneurial angst, figuring out how much to charge and more. They also give updates on AuditShark and Drip.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/ItC9pm9Hx0s\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://media.blubrry.com/startupsrestofus/www.project98.com/podcast/startups-for-the-rest-of-us-151.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 151 | Getting Paid Before You Build, Dealing with Entrpreneurial Angst, Figuring Out How Much to Charge and More Listener Questions", "Mike and Rob answer listener questions on getting paid before you build, dealing with entrpreneurial angst, figuring out how much to charge and more. They also give updates on AuditShark and Drip.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/ItC9pm9Hx0s\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://media.blubrry.com/startupsrestofus/www.project98.com/podcast/startups-for-the-rest-of-us-151.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 151 | Getting Paid Before You Build, Dealing with Entrpreneurial Angst, Figuring Out How Much to Charge and More Listener Questions", "Mike and Rob answer listener questions on getting paid before you build, dealing with entrpreneurial angst, figuring out how much to charge and more. They also give updates on AuditShark and Drip.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/ItC9pm9Hx0s\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://media.blubrry.com/startupsrestofus/www.project98.com/podcast/startups-for-the-rest-of-us-151.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 151 | Getting Paid Before You Build, Dealing with Entrpreneurial Angst, Figuring Out How Much to Charge and More Listener Questions", "Mike and Rob answer listener questions on getting paid before you build, dealing with entrpreneurial angst, figuring out how much to charge and more. They also give updates on AuditShark and Drip.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/ItC9pm9Hx0s\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://media.blubrry.com/startupsrestofus/www.project98.com/podcast/startups-for-the-rest-of-us-151.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        itemList.add(new EpisodeItem(new Episode("Episode 83 | HitTail & AuditShark: Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels", "Mike and Rob discuss Integration Marketing, Logo Design, Survey Analysis and Leaky Funnels.<img src=\"http://feeds.feedburner.com/~r/StartupsForTheRestOfUs/~4/9oVMEIXh-1w\" height=\"1\" width=\"1\"/>", new Date(System.currentTimeMillis()), "http://www.project98.com/podcast/startups-for-the-rest-of-us-083.mp3", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg", 44236023L), mListener));
        return itemList;
    }

    protected List<Item> getPodcastItems(OnPodcastClickListener mListener) {
        List<Item> itemList = new ArrayList<Item>();
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        itemList.add(new PodcastItem(new Podcast("Startups For the Rest of Us", "http://www.startupsfortherestofus.com", "Mike Taber and Rob Walling come together to share their insights and experience from the perspective of developers who built their respective companies without Angel or Venture Capital funding. Together, they share the things they've learned and are still learning as independent developers.", "http://www.startupsfortherestofus.com/wp-content/uploads/startup-fortherest-logo.png", "http://www.startupsfortherestofus.com/wp-content/uploads/sftrou_144x144.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Tech", "http://twit.tv/twit", "Your first podcast of the week is the last word in tech. Join Leo Laporte, Patrick Norton, Kevin Rose, John C. Dvorak, and other tech luminaries in a roundtable discussion of the latest trends in digital tech. 2005 People's Choice Podcast Award winner.", "http://feeds.twit.tv/podcasts/coverart/twit1400audio.jpg", "http://feeds.twit.tv/podcasts/coverart/twit144audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("This Week in Startups", "http://thisweekinstartups.com", "Entrepreneur Jason Calacanis and a rotating group of guests experts bring you this weekly take on the best, wors, most outrageous and interesting stories from the world of the Web companies. Calacanis, a podcaster pioneer, gives you an insider's look at what's happening in the tech industry with his trademark blunt style and good humor. Looking to start your own company? Need strategies for improving your business or motivating your team? Just want to catch up on what's happening on Silicon Valley and beyond? Your jurney begins here.", "http://www.thisweekin.com/featured/FeatureBox_Startups.jpg", "http://thisweekinstartups.com/wp-content/uploads/2013/07/startups_audio.jpg"), mListener));
        itemList.add(new PodcastItem(new Podcast("Answer Me This!", "http://answermethis.wordpress.com", "Helen Zaltzman & Olly Mann answer the world's questions", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png", "http://1.gravatar.com/blavatar/daaccc2312dc64b7fbec9b83795f0595?s=96&d=http%3A%2F%2Fs2.wp.com%2Fi%2Fbuttonw-com.png"), mListener));
        long seed = System.nanoTime();
        Collections.shuffle(itemList, new Random(seed));
        return itemList;
    }
}
